// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU_x9KLHKEgJwauBZzmh3UrtNKco27rOo',
    appId: '1:655565727204:web:e8e99d5c28b39e586013f1',
    messagingSenderId: '655565727204',
    projectId: 'cashlyze-b156c',
    authDomain: 'cashlyze-b156c.firebaseapp.com',
    storageBucket: 'cashlyze-b156c.firebasestorage.app',
    measurementId: 'G-9M47CP74ME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQGZP4F8qZBK7eB7ZN1Bh836B1WYkOJAQ',
    appId: '1:655565727204:android:bf39e9508535052f6013f1',
    messagingSenderId: '655565727204',
    projectId: 'cashlyze-b156c',
    storageBucket: 'cashlyze-b156c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA39XAsbcUuKhepy0Q7CIlY2NSywOWAnOo',
    appId: '1:655565727204:ios:26b3ce595b611a676013f1',
    messagingSenderId: '655565727204',
    projectId: 'cashlyze-b156c',
    storageBucket: 'cashlyze-b156c.firebasestorage.app',
    iosBundleId: 'com.cashlyze.cashlyze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.cashlyze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU_x9KLHKEgJwauBZzmh3UrtNKco27rOo',
    appId: '1:655565727204:web:cee41a32a60285966013f1',
    messagingSenderId: '655565727204',
    projectId: 'cashlyze-b156c',
    authDomain: 'cashlyze-b156c.firebaseapp.com',
    storageBucket: 'cashlyze-b156c.firebasestorage.app',
    measurementId: 'G-RF25GMVHVE',
  );

}