name: Build and Deploy

on:
  push:
    branches:
      - development
      - prod
  pull_request:
    branches:
      - development
      - prod

jobs:
  release:
    uses: KameshEas/gha-templates/.github/workflows/flutter-release.yml@v1
    with:
      keystore-filename: cashlyze-release.jks
      artifact-prefix: cashlyze
      enable-shorebird: true
      enable-firebase-distribution: true
      enable-play-store: true
      enable-auto-versioning: true
    secrets: inherit
